spring.application.name=SpaMoonBeauty
server.port=8080

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/aura_spa2}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.sql.init.mode=never
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=false
spring.flyway.baseline-version=1
spring.flyway.clean-disabled=true
spring.flyway.validate-migration-naming=true
spring.jpa.open-in-view=false
spring.jpa.show-sql=false

spa.admin.username=${SPA_ADMIN_USERNAME:Julian}
spa.admin.password=${SPA_ADMIN_PASSWORD:Jrma221803}
