spring.application.name=sistema-spa
server.port=8080

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/aura_spa}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=false

spa.admin.username=${SPA_ADMIN_USERNAME:}
spa.admin.password=${SPA_ADMIN_PASSWORD:}