-- Current application schema. Only executed on an empty installation.
-- Existing installations adopt baseline 1 and MUST NOT execute this file.
CREATE TABLE branches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    sector VARCHAR(255),
    address VARCHAR(255),
    opening_hours VARCHAR(255),
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    active BOOLEAN NOT NULL
);

CREATE TABLE masseuses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    specialty VARCHAR(255),
    phone VARCHAR(255),
    email VARCHAR(255),
    active BOOLEAN NOT NULL
);

CREATE TABLE spa_services (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    category VARCHAR(255),
    description TEXT,
    duration_minutes INTEGER,
    price NUMERIC(38, 2),
    image_url VARCHAR(255),
    active BOOLEAN NOT NULL,
    featured BOOLEAN NOT NULL DEFAULT false
);

CREATE TABLE reservations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_id BIGINT NOT NULL,
    branch_id INTEGER NOT NULL,
    masseuse_id BIGINT,
    customer_name VARCHAR(255) NOT NULL,
    customer_id_number VARCHAR(255) NOT NULL,
    customer_phone VARCHAR(255) NOT NULL,
    customer_email VARCHAR(255) NOT NULL,
    reservation_date DATE NOT NULL,
    reservation_time VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    access_code_hash VARCHAR(64),
    CONSTRAINT fk_reservations_service FOREIGN KEY (service_id) REFERENCES spa_services(id),
    CONSTRAINT fk_reservations_branch FOREIGN KEY (branch_id) REFERENCES branches(id),
    CONSTRAINT fk_reservations_masseuse FOREIGN KEY (masseuse_id) REFERENCES masseuses(id)
);

CREATE TABLE reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name VARCHAR(255),
    branch_id INTEGER,
    rating INTEGER,
    comment VARCHAR(255),
    status VARCHAR(255)
);
